### PR TITLE
Post Hook Feature

### PR DESCRIPTION
**Pull request by peccu**
I implemented post hook feature.

I wanted to apply some template into existing files.
So I added hook before `fs.writeFileSync` to overwrite content.

Could you review this?

I couldn't test this in ava because of inquirer.prompt.

### CODE REVIEW

**Comment by saneef** [comment]
@peccu Thanks for the effort.

But, your use case seems like it can be solved by a handlebar helper function. Did you try?

**Comment by saneef** [comment]
I have created a sample project at https://github.com/saneef/qgen-sample-file-append, utilising handlebars to append a file.

**Comment by saneef** [comment]
qgen is intended to be used for scaffolding files or folder. You could use work arounds for this specific use case.

I would not like to inherit this as a core feature of qgen.

**Comment by peccu** [comment]
Thank you for your review and your example.
I didn't notice that I can do it by handlebars helper.
I'll write helpers.

**Pull request closed without merging**
